# Site settings
title: Unikornis Száraztészta
email: hello@szarazteszta.hu
phone: +36-30-999-9999

description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vestalux.github.io/teszta/" # the base hostname & protocol for your site

facebook_username: teszta
github_username:
logo: "img/logo.svg"
ga:
# Build settings
markdown: kramdown

collections:
  portfolio:
    output: true
    permalink: portfolio/:title/
